default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: agentkvt_development

test:
  <<: *default
  database: agentkvt_test

production:
  primary:
    <<: *default
    database: agentkvt_production
  cache:
    <<: *default
    database: agentkvt_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: agentkvt_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: agentkvt_production_cable
    migrations_paths: db/cable_migrate
