default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: agentkvt_development

test:
  <<: *default
  database: agentkvt_test

production:
  <<: *default
  database: agentkvt_production
